services:
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: test
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/data/mysql
            - ./src/sql/test.sql:/docker-entrypoint-initdb.d/init.sql
            - ./src/sql/tables.sql:/src/sql/tables.sql
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-p${MYSQL_ROOT_PASSWORD}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

volumes:
    mysql_data:
